### PR TITLE
Some small improvements.

### PR DESCRIPTION
**Pull request by Koubek**

### CODE REVIEW

**Comment by Koubek** [comment]
Sorry, I have unintentionally included something old (HEALTHCHECK proposal).

**Comment by Koubek** [comment]
Actually I can see it is OK. Sorry for the mess.

**Comment by freddydk** [comment]
The HealthCheck i have in the depot is:

HEALTHCHECK --interval=30s --timeout=10s CMD [ "powershell", ".\\Run\\HealthCheck.ps1" ]
And the HealthCheck does this:

try {
    $CustomConfigFile = Join-Path (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Service").FullName "CustomSettings.config"
    $CustomConfig = [xml](Get-Content $CustomConfigFile)
    $publicWebBaseUrl = $CustomConfig.SelectSingleNode("//appSettings/add[@key='PublicWebBaseUrl']").Value

    $result = Invoke-WebRequest -Uri "$publicWebBaseUrl/Health/System" -UseBasicParsing -TimeoutSec 10
    if ($result.StatusCode -eq 200 -and ((ConvertFrom-Json $result.Content).result)) {
        # Web Client Health Check Endpoint will test Web Client, Service Tier and Database Connection
        exit 0
    }
} catch {
}
exit 1

Which is doing a full stack health check (like D365 servers), not just TCP check.

Not sure why your pull request haven’t included this?

/Freddy

**Comment by freddydk** [comment]
Sorry too – I can see that you pulled master later and the healthcheck isn’t included.
(probably the same as you saw since you closed and reopened😊)

/Freddy

From: Freddy Kristiansen
Sent: 17. juli 2017 06:54
To: 'NAVDOCKER/GENERIC' <reply@reply.github.com>
Subject: RE: [NAVDOCKER/GENERIC] Some small improvements. (#7)

The HealthCheck i have in the depot is:

HEALTHCHECK --interval=30s --timeout=10s CMD [ "powershell", ".\\Run\\HealthCheck.ps1" ]

And the HealthCheck does this:

try {
    $CustomConfigFile = Join-Path (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Service").FullName "CustomSettings.config"
    $CustomConfig = [xml](Get-Content $CustomConfigFile)
    $publicWebBaseUrl = $CustomConfig.SelectSingleNode("//appSettings/add[@key='PublicWebBaseUrl']").Value

    $result = Invoke-WebRequest -Uri "$publicWebBaseUrl/Health/System" -UseBasicParsing -TimeoutSec 10
    if ($result.StatusCode -eq 200 -and ((ConvertFrom-Json $result.Content).result)) {
        # Web Client Health Check Endpoint will test Web Client, Service Tier and Database Connection
        exit 0
    }
} catch {
}
exit 1

Which is doing a full stack health check (like D365 servers), not just TCP check.

Not sure why your pull request haven’t included this?

/Freddy

**Pull request merged**
